# Model
device: cuda

alg_name: "EFK"
model_name: Qwen/Qwen2-Audio-7B-Instruct
model_class: Qwen2AudioForConditionalGeneration
tokenizer_class: AutoProcessor
tokenizer_name: Qwen/Qwen2-Audio-7B-Instruct
inner_params:
- language_model.model.layers.29.mlp.gate_proj.weight
- language_model.model.layers.29.mlp.up_proj.weight
- language_model.model.layers.29.mlp.down_proj.weight
- language_model.model.layers.30.mlp.gate_proj.weight
- language_model.model.layers.30.mlp.up_proj.weight
- language_model.model.layers.30.mlp.down_proj.weight
- language_model.model.layers.31.mlp.gate_proj.weight
- language_model.model.layers.31.mlp.up_proj.weight
- language_model.model.layers.31.mlp.down_proj.weight

archive: /work/b10902133/data/lalm-knowledge-editing/EasyEdit/results/EFK/Qwen2Audio/models/EFK/Qwen2-Audio-7B-Instruct-3600
model_parallel: False

# Method
alg: EFK
lr: 3e-4 #1e-5
edit_lr: 1e-2
lr_lr: 1e-3
seed: 42
cedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null

# Train
batch_size: 1
model_save_pt: 5000
silent: False
# max_epochs: 1
max_iters: 3600 #50000 # TODO: change to 50000 for real training
log_interval: 50
eval_log_interval: 50
final_eval: True
val_interval: 900
early_stop_patience: 5000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
debug: False
save: True # TODO: change to True for real training
verbose: True

val_batch_size: 1
accumulate_bs: 2
val_steps: 500 # only for debug
opt: RMSprop
grad_clip: 100.

# Output

results_dir: ./results/EFK/Qwen2Audio

# Audio
cache_dir: ./.cache
audio_root: /work/b10902133/data/lalm-knowledge-editing/dataset/audio_wavs

# Weights and Biases
wandb_enabled: True
wandb_project: LALM-Knowledge-Editing_EFK_Qwen2Audio_testing