# Model
device: cuda

model_name: nvidia/audio-flamingo-3-hf
model_class: AudioFlamingo3ForConditionalGeneration
tokenizer_class: AutoProcessor
tokenizer_name: nvidia/audio-flamingo-3-hf
inner_params:
- language_model.model.layers.25.mlp.gate_proj.weight
- language_model.model.layers.25.mlp.up_proj.weight
- language_model.model.layers.25.mlp.down_proj.weight
- language_model.model.layers.26.mlp.gate_proj.weight
- language_model.model.layers.26.mlp.up_proj.weight
- language_model.model.layers.26.mlp.down_proj.weight
- language_model.model.layers.27.mlp.gate_proj.weight
- language_model.model.layers.27.mlp.up_proj.weight
- language_model.model.layers.27.mlp.down_proj.weight



# Method
alg: EFK
lr: 3e-4 #1e-5
edit_lr: 1e-2
lr_lr: 1e-3
seed: 42
cedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
train_base: False
no_grad_layers: null
archive: null
model_parallel: True

# Train
batch_size: 1
model_save_pt: 5000
silent: False
# max_epochs: 1
max_iters: 3600 #50000 # TODO: change to 50000 for real training
log_interval: 50
eval_log_interval: 50
final_eval: True
val_interval: 900
early_stop_patience: 5000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
debug: False
save: True # TODO: change to True for real training
verbose: True

val_batch_size: 1
accumulate_bs: 2
val_steps: 500 # only for debug
opt: RMSprop
grad_clip: 100.

# Output

results_dir: ./results/EFK/AudioFlamingo3

# Audio
cache_dir: ./.cache
audio_root: ~/data/lalm-knowledge-editing/dataset/audio_wavs

# Weights and Biases
wandb_enabled: True
wandb_project: LALM-Knowledge-Editing_EFK_AudioFlamingo3